default_language_version:
  python: python3
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-added-large-files
  - id: check-builtin-literals
  - id: check-case-conflict
  - id: check-docstring-first
  - id: check-executables-have-shebangs
  - id: check-merge-conflict
  - id: check-toml
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: mixed-line-ending
  - id: sort-simple-yaml
  - id: trailing-whitespace
- repo: local
  hooks:
  - id: todo
    name: Check TODO
    language: pygrep
    entry: TODO
    args: [-i]
    types: [text]
    exclude: ^.pre-commit-config.yaml$
  - id: pytest
    name: pytest
    language: python
    entry: pytest
    args: [.github/workflows/daily.py, -v, --tb=short, -rxs, -W=error, --durations=0]
    types: [python]
    pass_filenames: false
    additional_dependencies:
    - pytest
    - bs4
    - requests
- repo: https://github.com/asottile/pyupgrade
  rev: v3.21.2
  hooks:
  - id: pyupgrade
    args: [--py314-plus]
