name: daily
on:
  push:
  schedule:
    - cron:  '* 0 * * *'  # M H d m w
jobs:
  snap_gh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install snapcraft
        run: |
          sudo snap install snapcraft --classic
          sudo snap install multipass --classic
          sudo snap install review-tools
          sudo chown root:root /  # fix root ownership
      - name: clone
        run: git clone https://github.com/casperdcl/cli --branch snap
      - name: build
        run: |
          pushd cli
          sudo snapcraft
          popd
      - name: deploy snap
        run: |
          echo "$SNAP_TOKEN" | base64 --decode | snapcraft login --with -
          sudo snapcraft push cli/gh_*.snap --release edge
        env:
          SNAP_TOKEN: ${{ secrets.SNAP_TOKEN_GH }}
