name: daily
on:
  push:
  schedule:
    - cron: '6 0 * * *'  # M H d m w (daily at 00:06)
jobs:
  snap-gh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: casperdcl/action-snapcraft@master
        with:
          use_lxd: true
      - name: clone source
        run: |
          git clone https://${GH_TOKEN}@github.com/casperdcl/cli --branch snap
          pushd cli
          git remote add upstream https://github.com/cli/cli
          git fetch upstream master
          git rebase upstream/master && git push -f
          popd
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN_GH }}
      - name: build snap
        shell: bash
        run: |
          pushd cli
          if [ -z "$(git log --since=1.day)" ]; then
            echo "no change so skipping"
          else
            sudo snapcraft --use-lxd
          fi
          popd
      - uses: casperdcl/action-snapcraft@master
        with:
          snapcraft_token: ${{ secrets.SNAP_TOKEN_GH }}
      - name: deploy snap
        shell: bash
        run: |
          if [ -n "$(ls cli/gh_*.snap 2>/dev/null)" ]; then
            sudo snapcraft push cli/gh_*.snap --release edge
          fi
