name: daily
on:
  push:
  schedule:
    - cron: '* 0 * * *'  # M H d m w
jobs:
  snap_gh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install snapcraft
        run: |
          sudo snap install snapcraft --classic
          sudo snap install lxd
          sudo chown root:root /  # fix root ownership
          sudo /snap/bin/lxd.migrate -yes
          sudo /snap/bin/lxd waitready
          sudo /snap/bin/lxd init --auto
      - name: clone
        run: git clone https://github.com/casperdcl/cli --branch snap
      - name: build
        run: |
          pushd cli
          sudo snapcraft --use-lxd
          popd
      - name: deploy snap
        run: |
          echo "$SNAP_TOKEN" | base64 --decode | snapcraft login --with -
          sudo snapcraft push cli/gh_*.snap --release edge
        env:
          SNAP_TOKEN: ${{ secrets.SNAP_TOKEN_GH }}
