name: daily
on:
  push:
  schedule:
    - cron: '6 0 * * *'  # M H d m w (daily at 00:06)
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: set PYSHA
      run: echo "PYSHA=$(python -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pre-commit
        key: pre-commit|${{ env.PYSHA }}|${{ hashFiles('.pre-commit-config.yaml') }}
    - run: pip install -U pre-commit
    - run: pre-commit run -a --show-diff-on-failure
  shfmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v1
      with:
        go-version: 1.13.x
    - uses: actions/checkout@v2
    - uses: casperdcl/sh@action
  snap-gh:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: clone source
      run: |
        git clone https://${GITHUB_TOKEN}@github.com/casperdcl/cli --branch snap
        pushd cli
        git remote add upstream https://github.com/cli/cli
        git fetch upstream trunk && git fetch upstream --tags
        git config user.name "Casper da Costa-Luis"
        git config user.email casper.dcl@physics.org
        git rebase upstream/trunk && git push -f && git push --tags -f
        if [ -z "$(git log --since=1.day)" ]; then
          echo "no change so skipping"
          echo "skip=true" >> $GITHUB_ENV
        else
          echo "skip=" >> $GITHUB_ENV
        fi
        popd
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN_GH }}
    - uses: samuelmeuli/action-snapcraft@v1
      with:
        use_lxd: true
      if: '!env.skip'
    - name: build snap
      run: |
        pushd cli
        sg lxd -c 'snapcraft --use-lxd'
        popd
      if: '!env.skip'
    - uses: samuelmeuli/action-snapcraft@v1
      with:
        snapcraft_token: ${{ secrets.SNAP_TOKEN_GH }}
        skip_install: true
      if: '!env.skip'
    - name: deploy snap
      run: |
        if [ -n "$(ls cli/gh_*.snap 2>/dev/null)" ]; then
          sudo snapcraft push cli/gh_*.snap --release edge
        fi
      if: '!env.skip'
